### PR TITLE
Colorized toolbar

### PR DESCRIPTION
**Pull request by roboxue**
- [x] Toolbar with color
- [x] Description about toolbar to explain the action

### CODE REVIEW

**Comment by roboxue** [comment]
simulator screen shot dec 5 2015 16 59 04
simulator screen shot dec 5 2015 16 59 21
simulator screen shot dec 5 2015 16 59 36
simulator screen shot dec 5 2015 16 59 51

**Comment by roboxue** [comment]
simulator screen shot dec 5 2015 18 02 49

**Comment by roboxue** [comment]
simulator screen shot dec 5 2015 18 12 14

**Comment by pingzh** [comment]
LGTM

**Comment by buy** [comment]
gogogo :ship:

**Pull request merged**
